[package]
name = "vmlb"
version = "0.1.0"
edition = "2021"
authors = ["Sherlock Holo <sherlockya at gmail.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    ".",
    "agent",
]

[dependencies]
