apiVersion: v1
kind: ServiceAccount
metadata:
  name: vmlb
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmlb-role

rules:
  - verbs:
      - list
      - watch
      - get

    apiGroups: [ '*' ]
    resources:
      - nodes

  - verbs:
      - get
      - watch
      - list
      - patch
      - post
      - update
      - put
      - delete

    apiGroups: [ '*' ]
    resources:
      - services

  - verbs: [ '*' ]
    apiGroups: [ '*' ]
    resources:
      - services/status
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vmlb-role-bind

subjects:
  - kind: ServiceAccount
    name: vmlb
    namespace: kube-system

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vmlb-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmlb
  namespace: kube-system
  labels:
    app: vmlb

spec:
  selector:
    matchLabels:
      app: vmlb
  template:
    metadata:
      labels:
        app: vmlb

    spec:
      containers:
        - name: controller
          image: sherlockholo/vmlb:0.1.0

          args:
            - http://example.com:8599

          resources:
            requests:
              memory: 128Mi

      serviceAccountName: vmlb
